(()=>{
window.KOKORYO_PACKS=window.KOKORYO_PACKS||{};
window.KOKORYO_PACKS.pack2={
 id:'pack2',
 name:'追加パック2',
 normalCards:[
  {
   key:'N26',name:'一斉採用',type:'N',vp:1,implemented:true,
   special:'massRecruitment',
   costText:'🎲1/2＋資金5',
   effectText:'設置時：全プレイヤーは雇用キャラクターを1人雇用する。設置したプレイヤーは、2人プレイなら命令書1枚、3人プレイなら2枚、4人以上なら3枚を獲得する。',
   installSpec:{faces:[[1,2]],resources:{y:5}}
  },
  {
   key:'N27',name:'レベルアップ',type:'N',vp:2,implemented:true,
   special:'castLevelUp',
   costText:'🎲3＋🎲4＋🎲5＋食料5',
   effectText:'設置時：自分の雇用キャラクター1人を選び、レアリティを1段階上げる。N→R、R→SR、SR→SSR。通常のレベルアップではSSRからURにはならない。',
   installSpec:{faces:[[3],[4],[5]],resources:{p:5}}
  },
  {
   key:'N28',name:'確定ガチャ',type:'N',vp:1,implemented:true,
   special:'guaranteedUR',
   costText:'🎲ANY＋資金5',
   effectText:'設置後、このカードを捨て、通常の雇用コストの2倍を支払うことでURを1人ランダムに雇用する。',
   installSpec:{any:1,resources:{y:5}}
  },
  {
   key:'N29',name:'受け入れ準備',type:'N',implemented:true,
   special:'hireCapacity',
   costText:'🎲ANY',
   effectText:'常時：自分の雇用上限を+1する。この効果は重複する。',
   installSpec:{any:1}
  },
  {
   key:'N30',name:'円満退職',type:'N',vp:3,implemented:true,
   special:'amicableRetirement',
   costText:'🎲5×3＋資金10',
   effectText:'設置時：雇用キャラクター1人を選び、そのキャラクターの通常の雇用コストを支払って解雇する。このターン、次に行う雇用1回は、解雇したキャラクターより高いレアリティが確定する。N→R以上、R→SR以上、SR→SSR以上、SSR→UR。URは選べない。',
   installSpec:{faces:[[5],[5],[5]],resources:{y:10}}
  },
  {
   key:'N31',name:'ハニートラップ',type:'N',vp:3,implemented:true,
   special:'honeyTrap',
   costText:'🎲2＋🎲3＋🎲ANY＋資金4',
   effectText:'設置時：他のプレイヤー1人を選び、そのプレイヤーの雇用キャラクター1人を選んで強制的に解雇する。',
   installSpec:{faces:[[2],[3]],any:1,resources:{y:4}}
  },
  {
   key:'N32',name:'トレード',type:'N',vp:2,implemented:true,
   special:'employeeTrade',
   costText:'🎲1＋🎲6',
   effectText:'設置時：他のプレイヤー1人を選ぶ。自分と選ばれたプレイヤーは、それぞれ自分の雇用キャラクター1人を選び、その2人を交換する。',
   installSpec:{faces:[[1],[6]]}
  },
  {
   key:'N33',name:'W雇用',type:'N',implemented:true,
   special:'doubleHire',
   costText:'🎲ANY',
   effectText:'通常の雇用を行うとき、この設置済みカードを捨てることで、その雇用で雇用キャラクターを2人雇用する。',
   installSpec:{any:1}
  },
  {
   key:'N34',name:'サプライズスペシャルガチャ',type:'N',vp:3,implemented:true,
   special:'surpriseSpecialGacha',
   costText:'🎲ANY×3＋資金8',
   effectText:'設置時：SSR以下の好きな雇用キャラクター1人を選んで雇用する。URは選べない。',
   installSpec:{any:3,resources:{y:8}}
  },
  {
   key:'N35',name:'派遣会社',type:'N',vp:3,implemented:true,
   special:'staffingAgency',
   costText:'🎲ANY×2＋資金4＋食料4＋兵力4',
   effectText:'常時：他のプレイヤーが雇用するたび、命令書1枚を獲得し、プレイヤー人数に応じて資金・食料・兵力をそれぞれ獲得する。2人：各3、3人：各2、4人以上：各1。',
   installSpec:{any:2,resources:{y:4,p:4,r:4}}
  }
 ],
 casts:{
  CUR10:{id:'CUR10',name:'ハインケル',title:'聖騎士',rarity:'UR',uniqueAbility:'神託',personKey:'heinkel'},
  CUR11:{id:'CUR11',name:'シアン',title:'街の小さな王女様',rarity:'UR',uniqueAbility:'貢ぎ物',personKey:'cian'},
  CUR12:{id:'CUR12',name:'ジル',title:'叛逆の商人',rarity:'UR',uniqueAbility:'デッドマンズトリガー',personKey:'jill'},
  CN5:{id:'CN5',name:'モノマネ師',rarity:'N',mimicMaterial:true,noCommonDie:true,abilityText:'合成時：同レアリティの必要素材1人分として代用できる。雇用時には何も獲得しない。'},
  CR5:{id:'CR5',name:'モノマネ師',rarity:'R',mimicMaterial:true,noCommonDie:true,abilityText:'合成時：同レアリティの必要素材1人分として代用できる。雇用時には何も獲得しない。'},
  CSR7:{id:'CSR7',name:'モノマネ師',rarity:'SR',mimicMaterial:true,noCommonDie:true,abilityText:'合成時：同レアリティの必要素材1人分として代用できる。雇用時には何も獲得しない。'},
  CN6:{id:'CN6',name:'ドッペルゲンガー',rarity:'N',doppelganger:true,noCommonDie:true,abilityText:'雇用時：全プレイヤーの雇用キャラクターから同レアリティの別キャラクター1人を選び、その固有効果をこの個体が永久にコピーする。対象がいない場合はコピーなしで確定する。'},
  CR6:{id:'CR6',name:'ドッペルゲンガー',rarity:'R',doppelganger:true,noCommonDie:true,abilityText:'雇用時：全プレイヤーの雇用キャラクターから同レアリティの別キャラクター1人を選び、その固有効果をこの個体が永久にコピーする。対象がいない場合はコピーなしで確定する。'},
  CSR8:{id:'CSR8',name:'ドッペルゲンガー',rarity:'SR',doppelganger:true,noCommonDie:true,abilityText:'雇用時：全プレイヤーの雇用キャラクターから同レアリティの別キャラクター1人を選び、その固有効果をこの個体が永久にコピーする。対象がいない場合はコピーなしで確定する。'},
  CSSR7:{id:'CSSR7',name:'ドッペルゲンガー',rarity:'SSR',doppelganger:true,noCommonDie:true,abilityText:'雇用時：全プレイヤーの雇用キャラクターから同レアリティの別キャラクター1人を選び、その固有効果をこの個体が永久にコピーする。対象がいない場合はコピーなしで確定する。'},
  CUR13:{id:'CUR13',name:'ドッペルゲンガー',title:'',rarity:'UR',doppelganger:true,doppelUniqueException:true,synthesisOnly:true,noCommonDie:true,abilityText:'雇用時：全プレイヤーの雇用キャラクターから同レアリティの別キャラクター1人を選び、その固有効果をこの個体が永久にコピーする。対象がいない場合はコピーなしで確定する。URの同一人物・同名雇用制限の例外として複数雇用できる。'}
 },
 castIds:['CUR10','CUR11','CUR12','CN5','CR5','CSR7','CN6','CR6','CSR8','CSSR7','CUR13'],
 castSynthesis:{CSR7:'CSSR7',CSR8:'CSSR7',CSSR7:'CUR13'},
 characters:{
  P19:{name:'ノエル',title:'',gender:'男性',group:'noel',selectLabel:'ノエル',uniqueAbility:'神託'},
  P20:{name:'ノエル',title:'',gender:'女性',group:'noel',selectLabel:'ノエル',uniqueAbility:'神託'},
  P21:{name:'シエル',title:'',gender:'男性',group:'ciel',selectLabel:'シエル',uniqueAbility:'貢ぎ物'},
  P22:{name:'シエル',title:'',gender:'女性',group:'ciel',selectLabel:'シエル',uniqueAbility:'貢ぎ物'},
  P23:{name:'ヴァレンタイン',title:'',gender:'男性',group:'valentine',selectLabel:'ヴァレンタイン',uniqueAbility:'デッドマンズトリガー'},
  P24:{name:'ヴァレンタイン',title:'',gender:'女性',group:'valentine',selectLabel:'ヴァレンタイン',uniqueAbility:'デッドマンズトリガー'}
 },
 characterFamilies:[
  {id:'noel',label:'ノエル',packId:'pack2',versions:[{id:'oracle',label:'神託',male:'P19',female:'P20'}]},
  {id:'ciel',label:'シエル',packId:'pack2',versions:[{id:'tribute',label:'貢ぎ物',male:'P21',female:'P22'}]},
  {id:'valentine',label:'ヴァレンタイン',packId:'pack2',versions:[{id:'deadMansTrigger',label:'デッドマンズトリガー',male:'P23',female:'P24'}]}
 ],
 legends:[
  {id:'LL10',tier:'lower',name:'大企業',vp:0,special:'bigCompany',costText:'🎲3＋🎲4＋資金10',facesExact:[3,4],cost:{y:10},specialConfig:{vpEmployeeCount:true,hireLimitBonus:1},effectText:'常時：自分の雇用上限を+1する。このカードのVPは、自分の雇用キャラクター1人につき1VP。'},
  {id:'LL11',tier:'lower',name:'特需',vp:5,special:'specialProcurement',costText:'🎲1＋🎲1＋🎲5＋🎲5',facesExact:[1,1,5,5],effectText:'獲得時：自分は好きな資源を合計15個獲得する。他のプレイヤーはそれぞれ好きな資源を合計5個獲得する。'},
  {id:'LL12',tier:'lower',name:'ナーロッパ祭',vp:0,special:'naroppaFestival',costText:'🎲ANY×3＋好きな資源10',anyDice:3,freeResourceCost:10,specialConfig:{standardPrintedVpMultiplier:2,standardKeys:['S1','S2','S3','S4','S5','S6','S7','S8','S9','S10']},effectText:'このカードのVPは、自分の設置済みスタンダードカードS1～S10の印刷VP合計の2倍。'},
  {id:'LU10',tier:'upper',name:'ナーロッパギルド',vp:0,special:'naroppaGuild',costText:'🎲1×2＋🎲2×2＋🎲3×2＋🎲4×2＋🎲5×2＋🎲6×2',facesExact:[1,1,2,2,3,3,4,4,5,5,6,6],specialConfig:{totalResourceVp:{divisor:3,round:'floor'}},effectText:'このカードのVPは、自分の資金・食料・兵力の合計3個につき1VP（端数切り捨て）。'},
  {id:'LU11',tier:'upper',name:'アーレア・ヤクタ・エスト',vp:5,special:'aleaIactaEst',costText:'🎲ANY×8',anyDice:8,effectText:'1ターンに1回、資金10・食料10・兵力10を支払うことで、そのターンのターン開始時に振ったサイコロと同じ個数の実サイコロを追加で振る。ターン開始時効果は再発動しない。'},
  {id:'LU12',tier:'upper',name:'ナーロッパワーク斡旋所',vp:7,special:'naroppaWorkAgency',costText:'🎲2＋🎲4＋🎲6＋資金5＋食料5＋兵力5',facesExact:[2,4,6],cost:{y:5,p:5,r:5},effectText:'1ターンに1回、自分の雇用キャラクター1人を解雇し、そのキャラクターと同じレアリティ以上の雇用キャラクターをランダムに1人雇用する。新しい個体として扱い、初回効果は再び発動できる。N→N以上、R→R以上、SR→SR以上、SSR→SSR以上、UR→UR。'}
 ]
};
})();
